# Generated by Django 5.1.3 on 2024-12-05 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_storage", "0002_remove_country_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="score",
            field=models.DecimalField(decimal_places=1, max_digits=3, null=True),
        ),
    ]
