# Generated by Django 5.1.3 on 2024-12-05 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("db_storage", "0003_alter_movie_score"),
    ]

    operations = [
        migrations.AlterField(
            model_name="movie",
            name="score",
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3),
            preserve_default=False,
        ),
    ]
